#!/usr/bin/env python3
"""Embed the top-level Vibio HTML pages into a C header the kernel links in.

This makes the browser's built-in pages available with no disk and no file on
the boot medium, so they work on real hardware (NVMe / USB boot) where the
kernel's own AHCI/FAT32 driver finds no device and where the boot medium may not
carry the HTML files.

Run from build.ps1 (pure standard-library Python, no Pillow), or by hand:

    py tools/make_html.py

It writes src/kernel/html_generated.h, which the kernel includes.
"""
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ASSETS = os.path.join(ROOT, "Assets")
OUT = os.path.join(ROOT, "src", "kernel", "html_generated.h")


def short_name(base, ext):
    """8.3 upper-case name (e.g. START.HTM) so it matches link hrefs."""
    base = "".join(c for c in base.upper() if c.isalnum())[:8]
    return base + "." + ext.upper()[:3]


def c_ident(name):
    return "vibio_html_" + name.replace(".", "_").lower()


def collect():
    pages = []
    if not os.path.isdir(ASSETS):
        return pages
    for entry in sorted(os.listdir(ASSETS)):
        path = os.path.join(ASSETS, entry)
        if not os.path.isfile(path):
            continue
        base, ext = os.path.splitext(entry)
        ext = ext.lstrip(".").upper()
        if ext not in ("HTM", "HTML") or not base:
            continue
        with open(path, "rb") as f:
            data = f.read()
        pages.append((short_name(base, ext), data))
    return pages


def main():
    pages = collect()
    lines = []
    lines.append("/* Generated by tools/make_html.py - do not edit by hand. */")
    lines.append("/* Built-in browser pages, embedded so they need no disk. */")
    lines.append("#ifndef VIBIO_HTML_GENERATED_H")
    lines.append("#define VIBIO_HTML_GENERATED_H")
    lines.append("")

    for name, data in pages:
        ident = c_ident(name)
        lines.append("static const vibio_u8 %s[%d] = {" % (ident, len(data)))
        row = []
        for i, b in enumerate(data):
            row.append("%d," % b)
            if len(row) == 20:
                lines.append("    " + "".join(row))
                row = []
        if row:
            lines.append("    " + "".join(row))
        lines.append("};")
        lines.append("")

    lines.append("typedef struct {")
    lines.append("    const char *name;")
    lines.append("    const vibio_u8 *data;")
    lines.append("    vibio_u32 length;")
    lines.append("} VibioBuiltinHtml;")
    lines.append("")
    lines.append("static const VibioBuiltinHtml vibio_builtin_html[] = {")
    for name, data in pages:
        lines.append('    {"%s", %s, %d},' % (name, c_ident(name), len(data)))
    lines.append("};")
    lines.append("")
    lines.append("#define VIBIO_BUILTIN_HTML_COUNT %d" % len(pages))
    lines.append("")
    lines.append("#endif /* VIBIO_HTML_GENERATED_H */")

    with open(OUT, "w", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    print("Wrote", OUT, "with", len(pages), "page(s)")


if __name__ == "__main__":
    main()
