#!/usr/bin/env python3
"""Convert selected Vibio PNG app/UI icons into a C header of pre-scaled,
straight-alpha 0xAARRGGBB pixel arrays the kernel can blit directly.

Run this whenever the source icons in Assets/Icons change:

    py tools/make_icons.py

It writes src/kernel/icons_generated.h, which the kernel includes. Kept out of
build.ps1 on purpose so the normal build stays Pillow-free and deterministic.
"""
import os
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "src", "kernel", "icons_generated.h")

# (c_name, source_png_relative, size_px). Source is the 256px master, scaled
# down with a high-quality filter to the exact on-screen size so the kernel can
# blit 1:1 with no runtime scaling.
ICONS = [
    ("system_36",   "Assets/Icons/system/vibio_system_256.png",       36),
    ("system_26",   "Assets/Icons/system/vibio_system_256.png",       26),
    ("terminal_36", "Assets/Icons/terminal/vibio_terminal_256.png",   36),
    ("terminal_26", "Assets/Icons/terminal/vibio_terminal_256.png",   26),
    ("search_18",   "Assets/Icons/search_ui/vibio_search_ui_256.png",  18),
    ("wifi_20",     "Assets/Icons/wifi_ui/vibio_wifi_ui_256.png",      20),
    ("sound_20",    "Assets/Icons/Sound_Icon/Sound Icon.png",          20),
    ("power_20",    "Assets/Icons/Power/Power_Icon.png",               20),
    ("restart_18",  "Assets/Icons/Power/Restart_icon.png",             18),
    ("browser_36",  "Assets/Icons/files/vibio_files_256.png",          36),
    ("browser_26",  "Assets/Icons/files/vibio_files_256.png",          26),
]


def convert(c_name, src_rel, size):
    img = Image.open(os.path.join(ROOT, src_rel)).convert("RGBA")
    img = img.resize((size, size), Image.LANCZOS)
    px = img.load()
    words = []
    for y in range(size):
        for x in range(size):
            r, g, b, a = px[x, y]
            words.append((a << 24) | (r << 16) | (g << 8) | b)
    return words


def main():
    lines = []
    lines.append("/* Generated by tools/make_icons.py - do not edit by hand. */")
    lines.append("/* Each pixel is 0xAARRGGBB straight alpha; blit with draw_icon_image. */")
    lines.append("#ifndef VIBIO_ICONS_GENERATED_H")
    lines.append("#define VIBIO_ICONS_GENERATED_H")
    lines.append("")
    for c_name, src_rel, size in ICONS:
        words = convert(c_name, src_rel, size)
        lines.append("#define VIBIO_ICON_%s_SIZE %d" % (c_name.upper(), size))
        lines.append("static const vibio_u32 vibio_icon_%s[%d] = {" % (c_name, size * size))
        row = []
        for i, w in enumerate(words):
            row.append("0x%08X," % w)
            if len(row) == 8:
                lines.append("    " + "".join(row))
                row = []
        if row:
            lines.append("    " + "".join(row))
        lines.append("};")
        lines.append("")
    lines.append("#endif /* VIBIO_ICONS_GENERATED_H */")

    with open(OUT, "w", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    print("Wrote", OUT)


if __name__ == "__main__":
    main()
