#!/usr/bin/env python3
"""Convert real desktop wallpaper images into a C header the Vibio kernel can
render directly as the desktop background.

This is the HONEST wallpaper path. Vibio has no in-kernel JPEG/PNG decoder for
arbitrary photos and no post-boot USB mass-storage driver, so it cannot read
G:\\Backgrounds at run time. Instead - exactly like icons_generated.h and
fonts_generated.h - the images are converted on the host at build time into
pre-scaled straight-RGB 0xAARRGGBB pixel arrays that get compiled into
KERNEL.BIN. The wallpaper picker then lists them as real, rendering choices.

Run this whenever the source backgrounds change:

    py tools/make_wallpapers.py                 # default source: G:\\Backgrounds
    py tools/make_wallpapers.py --src "D:\\Pics"

It writes src/kernel/wallpapers_generated.h, which the kernel includes. Kept out
of build.ps1 on purpose (the normal build stays Pillow-free and never depends on
the removable G: drive being attached). The source folder is only ever READ.

Each image is scaled to fit within MAX_DIM on its longest side (preserving
aspect) to bound how much the kernel binary grows. The kernel scales the stored
image up to cover the framebuffer at draw time.
"""
import argparse
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "src", "kernel", "wallpapers_generated.h")

# Longest-side cap for the stored bitmap. Kept at 512 for BOOT SAFETY: the boot
# stage loads the kernel at the fixed address 0x100000, and OVMF/QEMU only hands
# out a few MB of contiguous conventional memory there - a ~7.7 MB KERNEL.BIN
# (768px wallpapers) was rejected with "Could not load KERNEL.BIN", while the
# ~3.7 MB image (512px) loads on both QEMU and the real laptop. The blocky look
# is fixed in the kernel instead, by BILINEAR upscaling (draw_wallpaper_image) -
# that removes the hard pixel squares without growing KERNEL.BIN at all.
MAX_DIM = 512
EXTS = (".jpg", ".jpeg", ".png", ".bmp")


def short_label(filename):
    stem = os.path.splitext(os.path.basename(filename))[0]
    out = []
    for ch in stem:
        if ch.isalnum():
            out.append(ch.upper())
        elif ch in " -_":
            out.append(" ")
    label = "".join(out).strip()
    while "  " in label:
        label = label.replace("  ", " ")
    if not label:
        label = "WALLPAPER"
    return label[:18]


def convert(path):
    from PIL import Image
    img = Image.open(path).convert("RGBA")
    w, h = img.size
    if max(w, h) > MAX_DIM:
        if w >= h:
            nh = max(1, h * MAX_DIM // w)
            img = img.resize((MAX_DIM, nh), Image.LANCZOS)
        else:
            nw = max(1, w * MAX_DIM // h)
            img = img.resize((nw, MAX_DIM), Image.LANCZOS)
    w, h = img.size
    px = img.load()
    words = []
    for y in range(h):
        for x in range(w):
            r, g, b, a = px[x, y]
            # Wallpaper is opaque; force full alpha so it composites as a solid
            # base layer regardless of the source image's transparency.
            words.append((0xFF << 24) | (r << 16) | (g << 8) | b)
    return w, h, words


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", default="G:\\Backgrounds",
                    help="Folder of source wallpaper images (read-only).")
    args = ap.parse_args()

    images = []
    if os.path.isdir(args.src):
        for name in sorted(os.listdir(args.src)):
            if name.lower().endswith(EXTS):
                images.append(os.path.join(args.src, name))
    else:
        print("make_wallpapers: source folder not found: %s (emitting empty set)" % args.src)

    entries = []
    lines = []
    lines.append("/* Generated by tools/make_wallpapers.py - do not edit by hand. */")
    lines.append("/* Real desktop wallpapers converted from %s. */" % args.src)
    lines.append("/* Each pixel is 0xAARRGGBB (opaque); the kernel scales to cover the screen. */")
    lines.append("#ifndef VIBIO_WALLPAPERS_GENERATED_H")
    lines.append("#define VIBIO_WALLPAPERS_GENERATED_H")
    lines.append("")

    have_pillow = True
    if images:
        try:
            import PIL  # noqa: F401
        except Exception:
            have_pillow = False
            print("make_wallpapers: Pillow not installed; emitting empty set.")

    if not have_pillow:
        images = []

    for i, path in enumerate(images):
        try:
            w, h, words = convert(path)
        except Exception as exc:
            print("make_wallpapers: skipping %s (%s)" % (path, exc))
            continue
        label = short_label(path)
        arr = "vibio_wallpaper_%d" % i
        lines.append("static const vibio_u32 %s[%d] = {" % (arr, len(words)))
        row = []
        for j, word in enumerate(words):
            row.append("0x%08X," % word)
            if len(row) == 12:
                lines.append("    " + "".join(row))
                row = []
        if row:
            lines.append("    " + "".join(row))
        lines.append("};")
        lines.append("")
        entries.append((label, w, h, arr))

    lines.append("typedef struct {")
    lines.append("    const char *name;")
    lines.append("    vibio_u32 width;")
    lines.append("    vibio_u32 height;")
    lines.append("    const vibio_u32 *pixels;")
    lines.append("} VibioWallpaperImage;")
    lines.append("")
    lines.append("#define VIBIO_WALLPAPER_COUNT %d" % len(entries))
    if entries:
        lines.append("static const VibioWallpaperImage vibio_wallpapers[VIBIO_WALLPAPER_COUNT] = {")
        for label, w, h, arr in entries:
            lines.append('    { "%s", %d, %d, %s },' % (label, w, h, arr))
        lines.append("};")
    else:
        lines.append("static const VibioWallpaperImage vibio_wallpapers[1] = {")
        lines.append('    { "", 0, 0, 0 },')
        lines.append("};")
    lines.append("")
    lines.append("#endif")
    lines.append("")

    with open(OUT, "w", newline="\n") as f:
        f.write("\n".join(lines))

    size = os.path.getsize(OUT)
    print("make_wallpapers: wrote %d wallpaper(s) to %s (%.1f KB header)" %
          (len(entries), OUT, size / 1024.0))
    return 0


if __name__ == "__main__":
    sys.exit(main())
