#!/usr/bin/env python3
"""Render Geist (UI) and JetBrains Mono (terminal) into bitmap glyph atlases the
kernel can blit, written to src/kernel/fonts_generated.h.

Each font/size emits:
  - a flat alpha-coverage byte array (all glyph bitmaps concatenated), and
  - a 95-entry glyph table for ASCII 32..126: {offset, w, h, advance, bx, top}.

The kernel draws text by walking the string, looking up each glyph, and
alpha-blending its coverage bitmap in the requested color. Geist is proportional
(per-glyph advance); JetBrains Mono is monospace (constant advance).

Run by hand when fonts/sizes change:  py tools/make_fonts.py
Kept out of build.ps1 so the normal build stays Pillow-free.
"""
import os
from PIL import Image, ImageDraw, ImageFont

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "src", "kernel", "fonts_generated.h")

FONTS = [
    ("geist_ui", "Assets/Fonts/Geist-Regular.ttf", 19),
    ("geist_sm", "Assets/Fonts/Geist-Regular.ttf", 14),
    ("jbm",      "Assets/Fonts/JetBrainsMono-Regular.ttf", 17),
]

FIRST, LAST = 32, 126


def render_font(c_name, path, px):
    font = ImageFont.truetype(os.path.join(ROOT, path), px)
    ascent, descent = font.getmetrics()
    line_h = ascent + descent

    alpha = bytearray()
    glyphs = []  # (offset, w, h, advance, bx, top)
    for code in range(FIRST, LAST + 1):
        ch = chr(code)
        advance = int(round(font.getlength(ch)))
        img = Image.new("L", (advance + px + 4, line_h + 4), 0)
        ImageDraw.Draw(img).text((2, 2), ch, font=font, fill=255)
        bbox = img.getbbox()
        if bbox is None:
            glyphs.append((len(alpha), 0, 0, advance, 0, 0))
            continue
        l, t, r, b = bbox
        crop = img.crop(bbox)
        gw, gh = r - l, b - t
        offset = len(alpha)
        alpha.extend(crop.tobytes())
        glyphs.append((offset, gw, gh, advance, l - 2, t - 2))

    return line_h, ascent, alpha, glyphs


def main():
    lines = []
    lines.append("/* Generated by tools/make_fonts.py - do not edit by hand. */")
    lines.append("#ifndef VIBIO_FONTS_GENERATED_H")
    lines.append("#define VIBIO_FONTS_GENERATED_H")
    lines.append("")
    lines.append("typedef struct {")
    lines.append("    vibio_u32 offset;")
    lines.append("    vibio_u8 w;")
    lines.append("    vibio_u8 h;")
    lines.append("    vibio_u8 advance;")
    lines.append("    vibio_s8 bx;")
    lines.append("    vibio_s8 top;")
    lines.append("} VibioGlyph;")
    lines.append("")

    for c_name, path, px in FONTS:
        line_h, ascent, alpha, glyphs = render_font(c_name, path, px)
        up = c_name.upper()
        lines.append("#define VIBIO_FONT_%s_LINE %d" % (up, line_h))
        lines.append("#define VIBIO_FONT_%s_ASCENT %d" % (up, ascent))
        lines.append("#define VIBIO_FONT_%s_FIRST %d" % (up, FIRST))
        lines.append("#define VIBIO_FONT_%s_LAST %d" % (up, LAST))
        lines.append("static const vibio_u8 vibio_font_%s_alpha[%d] = {" % (c_name, len(alpha)))
        row = []
        for i, v in enumerate(alpha):
            row.append("%d," % v)
            if len(row) == 24:
                lines.append("    " + "".join(row))
                row = []
        if row:
            lines.append("    " + "".join(row))
        lines.append("};")
        lines.append("static const VibioGlyph vibio_font_%s_glyphs[%d] = {" % (c_name, len(glyphs)))
        for (off, w, h, adv, bx, top) in glyphs:
            lines.append("    {%d,%d,%d,%d,%d,%d}," % (off, w, h, adv, bx, top))
        lines.append("};")
        lines.append("")

    lines.append("#endif /* VIBIO_FONTS_GENERATED_H */")

    with open(OUT, "w", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    print("Wrote", OUT)


if __name__ == "__main__":
    main()
