#!/usr/bin/env python3
"""Bake the default wallpaper into a C header the kernel can blit.

The source image is cover-cropped to 4:3 and downscaled to a compact base size;
the kernel bilinear-scales it up to whatever the framebuffer resolution is, so
the same data works in the 1024x768 VM and at the laptop's native resolution.

Run by hand when the wallpaper changes:  py tools/make_wallpaper.py
Kept out of build.ps1 so the normal build stays Pillow-free.
"""
import os
from PIL import Image, ImageOps

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "Assets", "background default.png")
OUT = os.path.join(ROOT, "src", "kernel", "wallpaper_generated.h")

BASE_W, BASE_H = 640, 480  # 4:3 base, kept small so KERNEL.BIN stays modest


def main():
    im = Image.open(SRC).convert("RGB")
    # Cover-crop to 4:3 and resize to the base size, centered.
    im = ImageOps.fit(im, (BASE_W, BASE_H), Image.LANCZOS, centering=(0.5, 0.5))
    px = im.load()

    lines = []
    lines.append("/* Generated by tools/make_wallpaper.py - do not edit by hand. */")
    lines.append("#ifndef VIBIO_WALLPAPER_GENERATED_H")
    lines.append("#define VIBIO_WALLPAPER_GENERATED_H")
    lines.append("#define VIBIO_WALLPAPER_W %d" % BASE_W)
    lines.append("#define VIBIO_WALLPAPER_H %d" % BASE_H)
    lines.append("static const vibio_u8 vibio_wallpaper_rgb[%d] = {" % (BASE_W * BASE_H * 3))
    row = []
    for y in range(BASE_H):
        for x in range(BASE_W):
            r, g, b = px[x, y]
            row.append("%d,%d,%d," % (r, g, b))
            if len(row) >= 12:
                lines.append("    " + "".join(row))
                row = []
    if row:
        lines.append("    " + "".join(row))
    lines.append("};")
    lines.append("#endif /* VIBIO_WALLPAPER_GENERATED_H */")

    with open(OUT, "w", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    print("Wrote", OUT, "(%dx%d)" % (BASE_W, BASE_H))


if __name__ == "__main__":
    main()
